title: Jerry Chen 
description: Graduate Research Assistant <br> Oden Institute, UT Austin
author: Jerry Chen
author_email: yuzhec@utexas.edu
theme: jekyll-theme-cayman
baseurl: "/jerrychen.github.io"
google_analytics: G-S87V41VV9S